# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "debian/stretch64"

  # Disable synced folders, to not have the Debian default install to not enter
  # an endless recursive dive starting from the symlink in test.
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # spin up vms
  vms = ['srv-librenms']
  vms.each do |server_name|
    config.vm.define server_name do |machine|
          machine.vm.hostname = server_name
          # Map port 80 in the VM to localhost port 8080 when using VirtualBox
          config.vm.provider "virtualbox" do |vb|
              machine.vm.network "forwarded_port", guest: 80, host: 8080
          end
    end
  end



  # define provisioning
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "test.yml"
    # ansible.groups = {
    #       "servers" => ["srv-a"],
    #       "workstations"  => ["ws-a"]
    # }
  end

end
